### ISSUE TITLE
extract-files.sh fails looking for vendor/bin/ffu

### ISSUE THREAD

**Issue by foresto** [Flamefire/android_device_sony_lilac#13]
Since 3246a33db3f2caadb2c3ff709f23d20a963338b6, extract-files.sh is now failing with the following error:

> sed: can't read ./../../../vendor/sony/lilac/proprietary/vendor/bin/ffu: No such file or directory

I checked two stock firmware images (47.2.A.11.228), and neither of them have an `ffu` in vendor/bin. What is it? Where is it supposed to come from?

**Comment by Flamefire** [comment]
If you check further down in that commit you see that this binary is copied by `sbin/ffu:vendor/bin/ffu` and it indeed is at `/sbin/ffu` in the stock image I checked (47.2.A.11.228)

Hope that helps

**Comment by foresto** [comment]
> it indeed is at /sbin/ffu in the stock image I checked (47.2.A.11.228)

Okay, this is really strange. Can you be more specific about which stock image you used? I've checked all of these firmware images:

G8441_T-Mobile NL_1311-0764_47.2.A.11.228_R2C
G8441_Customized UK_1310-6856_47.2.A.11.228_R2C
G8441_Customized US_1310-4371_47.2.A.11.228_R7C

In each of those, I checked both of these filesystem images:

system_X-FLASH-ALL-C93B.ext4
vendor_X-FLASH-ALL-C93B.ext4

There is no `sbin/ffu` or `vendor/bin/ffu` file in any of them. I checked again with the find command, just to be sure I'm not blind. And I've been building LineageOS using these same images for years, so I have no reason to doubt their integrity or my build process.

The extract script is unable to find `ffu`, either. So I dug deeper:

    $ ./extract-files.sh $BLOBDIR
    [...]
    sed: can't read ./../../../vendor/sony/lilac/proprietary/vendor/bin/ffu: No such file or directory
    $ cd ./../../../vendor/sony/lilac/proprietary/vendor/bin
    $ ls ffu
    ls: cannot access 'ffu': No such file or directory
    $ git remote -v
    github  https://github.com/Flamefire/android_vendor_sony_lilac (fetch)
    github  https://github.com/Flamefire/android_vendor_sony_lilac (push)

That looks like the script is looking for `ffu` in a repo-controlled directory that comes from your android_vendor_sony_lilac project. The file isn't there, either:

    https://github.com/Flamefire/android_vendor_sony_lilac/tree/lineage-17.1/proprietary/vendor/bin

However, `ffu` does exist in the lineage-19.1 branch of that project. So...

Where did the `ffu` in your lineage-19.1 branch originally come from?

Why are the lineage-17.1 proprietary-files-vendor.txt and extract-files.sh referencing it?

**Comment by Flamefire** [comment]
> Can you be more specific about which stock image you used?

IIRC G8441_Customized DE_47.2.A.11.228-R3C

> In each of those, I checked both of these filesystem images

The /sbin folder is part of the kernel img. Follow the instructions at https://forum.xda-developers.com/t/dumping-stock-firmware-to-use-for-lineage-custom-build.4034621 to get a complete dump.

> That looks like the script is looking for ffu in a repo-controlled directory that comes from your android_vendor_sony_lilac project. The file isn't there, either:

Almost yes. The `proprietary` folder contains pinned files. Upon completion of `extract-files.sh` it will also contain the copied files. As `ffu` is copied/extracted it is not there in the repo

> However, ffu does exist in the lineage-19.1 branch of that project.

That is a mistake and will be removed in the next commit.

> Where did the ffu in your lineage-19.1 branch originally come from?

It was a file from stock but modified. That is now done by the extract script since https://github.com/Flamefire/android_device_sony_lilac/commit/3246a33db3f2caadb2c3ff709f23d20a963338b6 so the (pinned) file is no longer needed.
